#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ALFC_SOAP.Droid.Resource", IsApplication=true)]

namespace ALFC_SOAP.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.XamForms.Mobile.Droid.Resource.String.ApplicationName = global::ALFC_SOAP.Droid.Resource.String.ApplicationName;
			global::Acr.XamForms.Mobile.Droid.Resource.String.Hello = global::ALFC_SOAP.Droid.Resource.String.Hello;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarLength = global::ALFC_SOAP.Droid.Resource.Attribute.ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarWidth = global::ALFC_SOAP.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahCircleColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahDelayMillis = global::ALFC_SOAP.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRadius = global::ALFC_SOAP.Droid.Resource.Attribute.ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimWidth = global::ALFC_SOAP.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahSpinSpeed = global::ALFC_SOAP.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahText = global::ALFC_SOAP.Droid.Resource.Attribute.ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextSize = global::ALFC_SOAP.Droid.Resource.Attribute.ahTextSize;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_errorstatus = global::ALFC_SOAP.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_successstatus = global::ALFC_SOAP.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbg = global::ALFC_SOAP.Droid.Resource.Drawable.roundedbg;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbgdark = global::ALFC_SOAP.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingImage = global::ALFC_SOAP.Droid.Resource.Id.loadingImage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressBar = global::ALFC_SOAP.Droid.Resource.Id.loadingProgressBar;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressWheel = global::ALFC_SOAP.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.textViewStatus = global::ALFC_SOAP.Droid.Resource.Id.textViewStatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loading = global::ALFC_SOAP.Droid.Resource.Layout.loading;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingimage = global::ALFC_SOAP.Droid.Resource.Layout.loadingimage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingprogress = global::ALFC_SOAP.Droid.Resource.Layout.loadingprogress;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.ApplicationName = global::ALFC_SOAP.Droid.Resource.String.ApplicationName;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.Hello = global::ALFC_SOAP.Droid.Resource.String.Hello;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.library_name = global::ALFC_SOAP.Droid.Resource.String.library_name;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarLength = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarWidth = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahCircleColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRadius = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimWidth = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahText = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextSize = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::ALFC_SOAP.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::ALFC_SOAP.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::ALFC_SOAP.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::ALFC_SOAP.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::ALFC_SOAP.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::ALFC_SOAP.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::ALFC_SOAP.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::ALFC_SOAP.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::ALFC_SOAP.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::ALFC_SOAP.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::ALFC_SOAP.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::ALFC_SOAP.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::ALFC_SOAP.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::ALFC_SOAP.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::ALFC_SOAP.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::ALFC_SOAP.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::ALFC_SOAP.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::ALFC_SOAP.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::ALFC_SOAP.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::ALFC_SOAP.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::ALFC_SOAP.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::ALFC_SOAP.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::ALFC_SOAP.Droid.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::ALFC_SOAP.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::ALFC_SOAP.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::ALFC_SOAP.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001a
			public const int ahBarColor = 2130771994;
			
			// aapt resource value: 0x7f010022
			public const int ahBarLength = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int ahBarWidth = 2130772001;
			
			// aapt resource value: 0x7f01001f
			public const int ahCircleColor = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int ahDelayMillis = 2130771998;
			
			// aapt resource value: 0x7f010020
			public const int ahRadius = 2130772000;
			
			// aapt resource value: 0x7f01001b
			public const int ahRimColor = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int ahRimWidth = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int ahSpinSpeed = 2130771997;
			
			// aapt resource value: 0x7f010017
			public const int ahText = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int ahTextColor = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int ahTextSize = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int auxiliary_view_position = 2130771989;
			
			// aapt resource value: 0x7f01000c
			public const int confirm_logout = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int done_button_background = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int done_button_text = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int extra_fields = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int fetch_user_info = 2130771981;
			
			// aapt resource value: 0x7f010012
			public const int foreground_color = 2130771986;
			
			// aapt resource value: 0x7f010016
			public const int horizontal_alignment = 2130771990;
			
			// aapt resource value: 0x7f010011
			public const int is_cropped = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int login_text = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int logout_text = 2130771983;
			
			// aapt resource value: 0x7f010007
			public const int multi_select = 2130771975;
			
			// aapt resource value: 0x7f010013
			public const int object_id = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int preset_size = 2130771984;
			
			// aapt resource value: 0x7f010008
			public const int radius_in_meters = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int results_limit = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int search_text = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int show_pictures = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int show_search_box = 2130771979;
			
			// aapt resource value: 0x7f010002
			public const int show_title_bar = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int style = 2130771988;
			
			// aapt resource value: 0x7f010005
			public const int title_bar_background = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int title_text = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_blue = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_likeboxcountview_border_color = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_likeboxcountview_text_color = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_likebutton_text_color = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_likeview_text_color = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_loginview_text_color = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_picker_search_bar_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_picker_search_bar_text = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050015
			public const int com_facebook_likeboxcountview_border_radius = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int com_facebook_likeboxcountview_border_width = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int com_facebook_likeboxcountview_caret_height = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int com_facebook_likeboxcountview_caret_width = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int com_facebook_likeboxcountview_text_padding = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int com_facebook_likeboxcountview_text_size = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int com_facebook_likebutton_compound_drawable_padding = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int com_facebook_likebutton_padding_bottom = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_likebutton_padding_left = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int com_facebook_likebutton_padding_right = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int com_facebook_likebutton_padding_top = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int com_facebook_likebutton_text_size = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_likeview_edge_padding = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_likeview_internal_padding = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_likeview_text_size = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_loginview_compound_drawable_padding = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_loginview_padding_bottom = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_loginview_padding_left = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_loginview_padding_right = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_loginview_padding_top = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_loginview_text_size = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_picker_divider_width = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_picker_place_image_size = 2131034112;
			
			// aapt resource value: 0x7f05001b
			public const int com_facebook_profilepictureview_preset_size_large = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int com_facebook_profilepictureview_preset_size_small = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int com_facebook_tooltip_horizontal_padding = 2131034140;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionChecked = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionShare = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionUnChecked = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_blue = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_blue_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_blue_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_blue_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_check = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_check_off = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_check_on = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_grey_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_button_grey_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_grey_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_button_like = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_button_like_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_button_like_background_selected = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_button_like_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_button_like_icon_selected = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_button_like_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_button_like_selected = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_close = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_inverse_icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_list_divider = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_list_section_header_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_loginbutton_silver = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_logo = 2130837529;
			
			// aapt resource value: 0x7f02003c
			public const int com_facebook_picker_default_separator_color = 2130837564;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_picker_item_background = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_picker_list_focused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_picker_list_longpressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_picker_list_pressed = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_picker_list_selector = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_picker_list_selector_background_transition = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_picker_list_selector_disabled = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_picker_magnifier = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_picker_top_button = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_place_default_icon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_profile_default_icon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_profile_picture_blank_portrait = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int com_facebook_profile_picture_blank_square = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int com_facebook_tooltip_black_background = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int com_facebook_tooltip_black_bottomnub = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int com_facebook_tooltip_black_topnub = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int com_facebook_tooltip_black_xout = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int com_facebook_tooltip_blue_background = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int com_facebook_tooltip_blue_bottomnub = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int com_facebook_tooltip_blue_topnub = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int com_facebook_tooltip_blue_xout = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int com_facebook_top_background = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int com_facebook_top_button = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_action_cancel = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_action_discard = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_action_new = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_errorstatus = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_successstatus = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Icon = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int roundedbg = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int roundedbgdark = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int splash = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int white = 2130837563;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090006
			public const int bottom = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int box_count = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int button = 2131296260;
			
			// aapt resource value: 0x7f090009
			public const int center = 2131296265;
			
			// aapt resource value: 0x7f09001e
			public const int com_facebook_body_frame = 2131296286;
			
			// aapt resource value: 0x7f090020
			public const int com_facebook_button_xout = 2131296288;
			
			// aapt resource value: 0x7f09000e
			public const int com_facebook_login_activity_progress_bar = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int com_facebook_picker_activity_circle = 2131296269;
			
			// aapt resource value: 0x7f090010
			public const int com_facebook_picker_checkbox = 2131296272;
			
			// aapt resource value: 0x7f090014
			public const int com_facebook_picker_checkbox_stub = 2131296276;
			
			// aapt resource value: 0x7f090018
			public const int com_facebook_picker_divider = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int com_facebook_picker_done_button = 2131296279;
			
			// aapt resource value: 0x7f090011
			public const int com_facebook_picker_image = 2131296273;
			
			// aapt resource value: 0x7f090015
			public const int com_facebook_picker_list_section_header = 2131296277;
			
			// aapt resource value: 0x7f09000c
			public const int com_facebook_picker_list_view = 2131296268;
			
			// aapt resource value: 0x7f090012
			public const int com_facebook_picker_profile_pic_stub = 2131296274;
			
			// aapt resource value: 0x7f09000f
			public const int com_facebook_picker_row_activity_circle = 2131296271;
			
			// aapt resource value: 0x7f09001d
			public const int com_facebook_picker_search_text = 2131296285;
			
			// aapt resource value: 0x7f090013
			public const int com_facebook_picker_title = 2131296275;
			
			// aapt resource value: 0x7f09001a
			public const int com_facebook_picker_title_bar = 2131296282;
			
			// aapt resource value: 0x7f090019
			public const int com_facebook_picker_title_bar_stub = 2131296281;
			
			// aapt resource value: 0x7f090016
			public const int com_facebook_picker_top_bar = 2131296278;
			
			// aapt resource value: 0x7f09001c
			public const int com_facebook_search_bar_view = 2131296284;
			
			// aapt resource value: 0x7f090022
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int com_facebook_tooltip_bubble_view_text_body = 2131296289;
			
			// aapt resource value: 0x7f09001f
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131296287;
			
			// aapt resource value: 0x7f090025
			public const int com_facebook_usersettingsfragment_login_button = 2131296293;
			
			// aapt resource value: 0x7f090023
			public const int com_facebook_usersettingsfragment_logo_image = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int com_facebook_usersettingsfragment_profile_name = 2131296292;
			
			// aapt resource value: 0x7f090007
			public const int inline = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int large = 2131296256;
			
			// aapt resource value: 0x7f09000a
			public const int left = 2131296266;
			
			// aapt resource value: 0x7f090028
			public const int loadingImage = 2131296296;
			
			// aapt resource value: 0x7f090026
			public const int loadingProgressBar = 2131296294;
			
			// aapt resource value: 0x7f090029
			public const int loadingProgressWheel = 2131296297;
			
			// aapt resource value: 0x7f090001
			public const int normal = 2131296257;
			
			// aapt resource value: 0x7f09001b
			public const int picker_subtitle = 2131296283;
			
			// aapt resource value: 0x7f09000b
			public const int right = 2131296267;
			
			// aapt resource value: 0x7f090002
			public const int small = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int standard = 2131296261;
			
			// aapt resource value: 0x7f090027
			public const int textViewStatus = 2131296295;
			
			// aapt resource value: 0x7f090008
			public const int top = 2131296264;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_friendpickerfragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_login_activity_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_picker_activity_circle_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int com_facebook_picker_checkbox = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_picker_image = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_picker_list_row = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_list_section_header = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_search_box = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_title_bar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_title_bar_stub = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_placepickerfragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_placepickerfragment_list_row = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_search_bar_layout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_tooltip_bubble = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_facebook_usersettingsfragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int loading = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int loadingimage = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int loadingprogress = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int alfcSQLlite = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001e
			public const int ApplicationName = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int Hello = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int app_id = 2131165216;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_choose_friends = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_dialogloginactivity_ok_button = 2131165184;
			
			// aapt resource value: 0x7f07001c
			public const int com_facebook_image_download_unknown_error = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int com_facebook_internet_permission_error_message = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int com_facebook_internet_permission_error_title = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_like_button_liked = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_like_button_not_liked = 2131165185;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_loading = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_loginview_cancel_action = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_loginview_log_in_button = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_loginview_log_out_action = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_loginview_log_out_button = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_loginview_logged_in_as = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_loginview_logged_in_using_facebook = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_logo_content_description = 2131165193;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_nearby = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_picker_done_button_text = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_placepicker_subtitle_format = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131165199;
			
			// aapt resource value: 0x7f070018
			public const int com_facebook_requesterror_password_changed = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int com_facebook_requesterror_permissions = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int com_facebook_requesterror_reconnect = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int com_facebook_requesterror_relogin = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int com_facebook_requesterror_web_login = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int com_facebook_tooltip_default = 2131165211;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_usersettingsfragment_log_in_button = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_usersettingsfragment_logged_in = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131165196;
			
			// aapt resource value: 0x7f07001f
			public const int library_name = 2131165215;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080004
			public const int Theme_Default = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int Theme_Splash = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_loginview_default_style = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_loginview_silver_style = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int tooltip_bubble_text = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] com_facebook_friend_picker_fragment = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_like_view = new int[] {
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 3
			public const int com_facebook_like_view_auxiliary_view_position = 3;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_foreground_color = 0;
			
			// aapt resource value: 4
			public const int com_facebook_like_view_horizontal_alignment = 4;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_style = 2;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
